pr pipeline 수정

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -36,5 +36,11 @@ jobs:
         create-new-comment: false
 
     - name: Get Error
-      if: steps.run-test.outputs.errors > 0 || steps.run-test.oupts.failures > 0
-      run: exit 1
+      run: |
+        echo "Coverage Errors - ${{ steps.run-test.outputs.errors }}"
+        echo "Coverage Failures - ${{ steps.run-test.outputs.failures }}"
+        echo "Coverage Skipped - ${{ steps.run-test.outputs.skipped }}"
+        echo "Coverage Tests - ${{ steps.run-test.outputs.tests }}"
+        echo "Coverage Time - ${{ steps.run-test.outputs.time }}"
+        if [[ ${{steps.run-test.outputs.errors}} > 0 || ${{steps.run-test.oupts.failures}} > 0 ]]; then
+            exit 1
